### ISSUE TITLE
attempt to call global 'GetMapNameByID' (a nil value)

### ISSUE THREAD

**Issue by Ookami313** [phanx-wow/HandyNotes_WellRead#4]
Received the following error when I moused over a book icon on my mini-map.

Date: 2018-07-28 17:11:54
ID: 6
Error occured in: Global
Count: 1
Message: ..\AddOns\HandyNotes_WellRead\Addon.lua line 279:
   attempt to call global 'GetMapNameByID' (a nil value)
Debug:
   (tail call): ?
   HandyNotes_WellRead\Addon.lua:279:
      HandyNotes_WellRead\Addon.lua:254
   [C]: ?
   HandyNotes\HandyNotes.lua:59:
      HandyNotes\HandyNotes.lua:54
   HandyNotes\HandyNotes.lua:169:
      HandyNotes\HandyNotes.lua:168
Locals:

Thanks.

**Comment by Phanx** [comment]
Fixed.
