### ISSUE TITLE
Already read books shown in the map

### ISSUE THREAD

**Issue by Naxterra** [phanx-wow/HandyNotes_WellRead#6]
WoW version: 8.0.1.27178
HandyNotes: Well Read version: 8.0.0.0
Issue: Even though I read books already, it is showing in my map as unread. It is occuring in my all characters. 
Example: Ashanvale - Astranaar - 34.47 50.01 - Sunwell - The Fall of Quel'Talas

**Comment by Phanx** [comment]
Can't reproduce. I created a fresh level 1 human, logged in with only HandyNotes and HandyNotes_WellRead enabled, verified that all books were showing on the map, ran to Stormwind, clicked books, verified that their icons disappeared from the map and minimap. I then logged out to the character selection screen, logged back in, and verified that the books I'd read were _not_ shown on the map, but all others were still shown.

There _is_ a long-standing issue in HandyNotes where it doesn't always update the minimap immediately when plugins remove icons, so icons might linger on the minimap for a bit after reading a new book. I didn't see this in my testing, so it might have finally been fixed, but if not, that may be what you're seeing.

Let me know if you can reproduce this with no other addons enabled _and_ it's not just the minimap update delay.

**Comment by Naxterra** [comment]
![2018-07-30_02-04-29](https://user-images.githubusercontent.com/41871948/43372074-f3a9a566-939c-11e8-9d70-0737673db3d1.png)

I disabled all addons except HandyNotes and HandyNotes Well Read. Book is still there.

**Comment by Phanx** [comment]
Alright, I created a fresh night elf and ran all the way to Astranaar. All 4 books there correctly disappeared from the map as soon as I clicked them.

At this point I'm not sure what else to try. If you want to gather some more information, open the `Addon.lua` file in a plain-text editor. You'll see lines that look like this:

```lua
	--print("ITEM_TEXT_BEGIN")
```

The two dashes at the beginning "comment out" the rest of the line, causing WoW to ignore it. Remove the two dashes in front of the `print` on each line where this pattern appears (the first one is on line 488). Save the file, and reload your UI in-game.

When the UI loads you should see (among other things) a list of messages in your chat frame like "COMPLETE: Book Name". Verify that the list matches what you see when you view the Well Read achievement in the achievement window.

If you click any book, you should see a "ITEM_TEXT_BEGIN" message.

If you hadn't read the book yet, "ITEM_TEXT_BEGIN" should be followed by a single "COMPLETE: Book Name" message matching the name of the book you just clicked, and then a "CHANGED" message indicating that the plugin has notified HandyNotes about the removed icon.

Let me know whether what you see is different than what I described above.

**Comment by Phanx** [comment]
Also, if you don't have any kind of error display, it would be helpful if you could enable one to check for error messages from WoW. [Bugger](/phanx-wow/Bugger), BugSack, or Swatter are all good options.

If you really don't want to install an addon, you can enable the game's built-in error display by running `/run SetCVar("scriptErrors", "1")` and reloading the UI, but it's going to pop up uncontrollably any time an error occurs and doesn't let you review errors later at your convenience so it's not really recommended. (Turn it off again by running the same command with a 0 instead of a 1).

If you get any errors that mention HandyNotes or HandyNotes_WellRead, post them here.

**Comment by Phanx** [comment]
Yes, I understood that, but that doesn't give me any new information that might let me figure out why it's happening.

Please follow the directions in my last post to enable debugging messages that will provide more information.
